photo_site/models.py
import os
import re
import random
from typing import Optional, List
from datetime import datetime

from peewee import SqliteDatabase, SQL, ForeignKeyField
import peewee as pw

import settings

db = SqliteDatabase(f"{settings.cwd}/data/db.sqlite3")


class Settings(pw.Model):
    id = pw.AutoField()
    key = pw.CharField(index=True, unique=True)
    value = pw.CharField()

    @staticmethod
    def by_key(key: str):
        try:
            setting = Settings.select().where(Settings.key == key).get()
            return setting.value
        except:
            return ""

    class Meta:
        database = db


class Album(pw.Model):
    id = pw.AutoField()
    date_added = pw.DateTimeField(default=datetime.now)
    name = pw.CharField(index=True, unique=True)
    description = pw.CharField(index=True)

    @property
    def random_img(self):
        assocs = PhotoAlbumAssoc.select().join(Photo).where((PhotoAlbumAssoc.album == self.id), (Photo.landscape == True))
        e = 1
        # assocs: List[PhotoAlbumAssoc] = PhotoAlbumAssoc.select().where(PhotoAlbumAssoc.album == self.id)
        try:
            assoc = random.choice(assocs)
            return assoc.photo
        except:
            pass

    class Meta:
        database = db


class Photo(pw.Model):
    id = pw.AutoField()
    date_added = pw.DateTimeField(default=datetime.now)

    title = pw.CharField(index=True, null=True, default="")
    filename: str = pw.CharField(index=True)
    camera = pw.CharField(index=True, null=True, default="")
    optics = pw.CharField(index=True, null=True, default="")
    date_taken = pw.DateTimeField(null=True)
    description = pw.CharField(default="", null=True)
    views = pw.IntegerField(default=0)
    location = pw.IntegerField(default='')
    height = pw.IntegerField()
    width = pw.IntegerField()
    landscape = pw.BooleanField(default=True)

    @property
    def album_ids(self):
        return [a.id for a in self.albums]

    @property
    def thumb(self):
        filename, ext = os.path.splitext(self.filename)
        return f"{filename}_thumb{ext}"

    class Meta:
        database = db


class PhotoAlbumAssoc(pw.Model):
    album = ForeignKeyField(Album, backref='photos', index=True)
    photo = ForeignKeyField(Photo, backref='albums', index=True)

    class Meta:
        database = db
        indexes = (
            (('album_id', 'photo_id'), True),
        )

photo_site/routes.py
from quart import render_template, request, redirect, url_for, jsonify, Blueprint, abort, flash, send_from_directory

import settings

bp_routes = Blueprint('routes', __name__)


@bp_routes.route('/')
@bp_routes.route('/<int:page>')
async def index(page: int = 1):
    from photo_site.models import Photo, PhotoAlbumAssoc, Album
    limit = 100
    offset = (page - 1) * limit
    photos = Photo.select(Photo).order_by(Photo.date_added.desc()).limit(limit).offset(offset)

    page_previous = None
    if page > 1:
        page_previous = url_for('routes.index', page=page - 1)

    page_next = url_for('routes.index', page=page + 1)
    return await render_template("index.html", photos=photos, page_next=page_next, page_previous=page_previous)


@bp_routes.route('/about')
async def about():
    from photo_site.models import Settings
    about_text = Settings.by_key("about")
    return await render_template("about.html", about_text=about_text)


@bp_routes.route('/a/')
async def albums_view():
    from photo_site.models import Album
    albums = Album.select().order_by(Album.date_added.desc())
    return await render_template("albums.html", albums=albums)


@bp_routes.route('/a/<int:album_id>')
@bp_routes.route('/a/<int:album_id>/<int:page>')
async def album_view(album_id, page: int = 1):
    from photo_site.models import Photo, PhotoAlbumAssoc, Album
    limit = 100
    offset = (page - 1) * limit

    album = Album.select().where(Album.id == album_id).get()
    photos = Photo.select(Photo).join(PhotoAlbumAssoc)\
        .where(PhotoAlbumAssoc.album == album_id).\
        order_by(Photo.date_added.desc())\
        .limit(limit).offset(offset)

    page_next = url_for("routes.album_view", album_id=album_id, page=page+1)
    page_previous = url_for("routes.album_view", album_id=album_id, page=page - (1 if page > 1 else 0))

    return await render_template("index_album.html", album=album, photos=photos, page_next=page_next, page_previous=page_previous)


@bp_routes.route('/a/<int:album_id>/p/<int:photo_id>')
async def album_photo_view(album_id: int, photo_id: int):
    from photo_site.models import Photo, PhotoAlbumAssoc, Album
    album = Album.select().where(Album.id == album_id).get()
    assoc = PhotoAlbumAssoc.select().where((PhotoAlbumAssoc.photo == photo_id),
                                           (PhotoAlbumAssoc.album == album.id)).get()
    albums = Album.select().order_by(Album.date_added.desc())

    q = Photo.select(Photo).join(PhotoAlbumAssoc)\
        .where(PhotoAlbumAssoc.album == album_id).\
        order_by(Photo.date_added.desc())
    photos = [p for p in q]

    # pagination stuff
    next_photo = ""
    previous_photo = ""
    for i, p in enumerate(photos):
        if p.id == photo_id:
            try:
                _p = photos[i + 1]
                next_photo = url_for("routes.album_photo_view", album_id=album.id, photo_id=_p.id)
            except:
                pass

            try:
                if i <= 0:
                    raise Exception("")
                _p = photos[i - 1]
                previous_photo = url_for("routes.album_photo_view", album_id=album.id, photo_id=_p.id)
            except:
                pass

    photo = Photo.select().where(Photo.id == photo_id).get()
    photo.albums = [a for a in Album.select().join(PhotoAlbumAssoc).where(PhotoAlbumAssoc.photo == photo)]

    return await render_template(
        "photo_view.html",
        album=album,
        albums=albums,
        photo=photo,
        next_photo=next_photo,
        previous_photo=previous_photo)


@bp_routes.route('/p/<int:photo_id>')
async def photo_view(photo_id):
    from photo_site.models import Photo, PhotoAlbumAssoc, Album

    photo = Photo.select().where(Photo.id == photo_id).get()

    # slow query ... whatever
    stream = Photo.select(Photo.id, Photo.date_added).order_by(Photo.date_added.desc())
    stream = [i.id for i in stream]

    # pagination stuff
    previous_photo = None
    next_photo = None
    for i, p_id in enumerate(stream):
        if p_id == photo_id:
            try:
                _p = stream[i + 1]
                next_photo = url_for("routes.photo_view", photo_id=_p)
            except:
                pass

            try:
                if i <= 0:
                    raise Exception("")
                _p = stream[i - 1]
                previous_photo = url_for("routes.photo_view", photo_id=_p)
            except:
                pass

    # :(
    photo.albums = [a for a in Album.select().join(PhotoAlbumAssoc).where(PhotoAlbumAssoc.photo == photo)]
    albums = [a for a in Album.select()]

    return await render_template(
        "photo_view.html",
        photo=photo,
        previous_photo=previous_photo,
        next_photo=next_photo,
        albums=albums
    )


@bp_routes.route('/p/static/<path:filename>')
async def photo_src(filename):
    from photo_site.models import Photo
    photo = Photo.select().where(Photo.filename == filename.replace("_thumb", "")).get()
    photo.views += 1
    photo.save()
    return await send_from_directory(settings.photos_dir, filename)


@bp_routes.errorhandler(404)
@bp_routes.errorhandler(500)
async def error(e):
    msg = str(e)
    try:
        if e.description:
            msg = f"{msg} - {e.description}"
    except:
        pass

    return await render_template("error.html", message=msg)


@bp_routes.route("/favicon.ico")
async def favicon():
    return "ok", 200

photo_site/templates/about.html
{% extends "base.html" %}
{% block content %}

<div class="container navtop">
  {% include "flash.html" %}

  <div class="row">
    <div class="col-md-6">
      {% if about_text %}
      {{ about_text | safe }}
      {% else %}
        Shrouded in mystery.
      {% endif %}
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-6">
      <span class="text-muted">
        <a href="https://github.com/sferdi0/quart-photo-site" target="_blank">Fork me on Github</a>
      </span>
    </div>
  </div>

</div>

{% endblock %}

photo_site/templates/admin.html
{% extends "base.html" %}
{% block content %}


<div class="container navtop">
  {% include "flash.html" %}

  <div class="row">
    <div class="col-md-6">
      <h2>Upload images</h2>
      <form action="/admin/p/add" method="POST" enctype="multipart/form-data">

        <label for="formFileMultiple" class="form-label">Only .jpg, 20MB max</label>
        <input class="form-control" name="photos" type="file" id="formFileMultiple" multiple />

        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>

  <br><br>

  {% if albums %}
  <div class="row">
    <div class="col-md-12">
      <h2>Albums</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for a in albums %}
          <tr>
            <th scope="row">{{ a.name }}</th>
            <td style="max-width:200px;">{{ a.description }}</td>
            <td>
              <button type="button" class="btn btn-primary"><i class="far fa-eye"></i></button>
              <a href="{{ url_for('routes_admin.album_edit', album_id=a.id) }}">
                <button type="button" class="btn btn-success"><i class="fas fa-edit"></i></button>
              </a>
              <a href="{{ url_for('routes_admin.album_delete', album_id=a.id) }}">
                <button type="button" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% endif %}

  <div class="row">
    <div class="col-md-6">
      <h4>Add album</h4>
      <a href="{{ url_for('routes_admin.album_add') }}">
        <button name="submit" type="submit" class="btn btn-primary">Add album</button>
      </a>
    </div>
  </div>

  <br><br>

  <div class="row">
    <div class="col-md-6">
      <h2>About page text</h2>
      <form action="{{ url_for('routes_admin.about_edit') }}" method="POST">
        <div class="mb-3">
          <label for="about_text">About text</label>
          <textarea id="about_text" placeholder="You can put HTML here..." name="about_text" cols="40" rows="8" class="form-control">{{ about_text }}</textarea>
        </div>

        <div class="mb-3">
          <button name="submit" type="submit" class="btn btn-primary">Edit about text</button>
        </div>
      </form>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <hr>
      <a href="{{ url_for('routes_admin.logout') }}">
        <button name="submit" type="submit" class="btn btn-danger">Logout</button>
      </a>
    </div>
  </div>
</div>

{% endblock %}

photo_site/templates/album_add.html
{% extends "base.html" %}
{% block content %}


<div class="container navtop">
  {% include "flash.html" %}

  <div class="row">
    <div class="col-md-6">
      <h4>Add album</h4>
      <form action="{{ url_for('routes_admin.album_add') }}" method="POST">
        <div class="mb-3">
          <label for="name">Name</label>
          <input id="name" name="name" placeholder="..." type="text" required="required" class="form-control">
        </div>
        <div class="mb-3">
          <label for="description">Description</label>
          <textarea id="description" placeholder="..." name="description" cols="40" rows="5" class="form-control"></textarea>
        </div>

        <br>
        <div class="mb-3">
          <button name="submit" type="submit" class="btn btn-primary">Add album</button>
        </div>
      </form>
    </div>
  </div>

</div>

{% endblock %}

photo_site/templates/album_edit.html
{% extends "base.html" %}
{% block content %}


<div class="container navtop">
  {% include "flash.html" %}

  <div class="row">
    <div class="col-md-6">
      <h4>Edit album</h4>
      <form action="{{ url_for('routes_admin.album_edit', album_id=album.id) }}" method="POST">
        <div class="mb-3">
          <label for="name">Name</label>
          <input id="name" name="name" placeholder="..." type="text" value="{{ album.name }}" required="required" class="form-control">
        </div>
        <div class="mb-3">
          <label for="description">Description</label>
          <textarea id="description" placeholder="..." name="description" cols="40" rows="5" class="form-control">{{ album.description }}</textarea>
        </div>

        <br>
        <div class="mb-3">
          <button name="submit" type="submit" class="btn btn-primary">edit album</button>
        </div>
      </form>
    </div>
  </div>

</div>

{% endblock %}

photo_site/templates/albums.html
{% extends "base.html" %}
{% block content %}

<div class="container-xl navtop">
  {% include "flash.html" %}

  <div class="row">
    {% for a in albums %}
    <div class="col-md-4">
      <a class="custom-card" href="{{ url_for('routes.album_view', album_id=a.id) }}">
        <div class="card">
          {% if a.random_img %}
            {% set img_url = url_for('routes.photo_src', filename=a.random_img.thumb) %}
          {% else %}
            {% set img_url = url_for('static', filename='gradient.jpg') %}
          {% endif %}
          <img class="card-img-top" src="{{ img_url }}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{ a.name }}</h5>
            {% if a.description | length > 150 %}
              <p class="card-text">{{ a.description[:150] }}...</p>
            {% else %}
              <p class="card-text">{{ a.description }}</p>
            {% endif %}
          </div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>

</div>

{% endblock %}

photo_site/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Photos{% endblock %}</title>
  <style>ul { list-style-type: none; }</style>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" integrity="undefined" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='photo.css') }}">
</head>
<body>

{% include "nav.html" %}

{% block content %} {% endblock %}

</body>
</html>

photo_site/templates/error.html
{% extends "base.html" %}
{% block content %}

<!--main-->
<div class="container" id="main">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading"></div>
        <div class="panel-body paste-body">
          <p>{{message}}</p>
          <br>
          <p>
            <a href="{{url_for('routes.index')}}">Go back to the main page</a>
          </p>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>
  </div>
  <!--/main-->
{% endblock %}

photo_site/templates/flash.html
{% with messages = get_flashed_messages() %}
  {% if messages %}
      <div class="alert alert-warning" role="alert">
        <ul class="flashes">
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
        </ul>
      </div>
  {% endif %}
{% endwith %}

photo_site/templates/index.html
{% extends "base.html" %}
{% block content %}
  {% include "flash.html" %}
  <div class="container-fluid navtop">
    {% if not photos %}
      Out of photos (ノಠ益ಠ)ノ彡┻━┻
    {% endif %}
    <ul class="stream">
      {% for p in photos %}
      <li>
        <a href="{{ url_for('routes.photo_view', photo_id=p.id) }}">
          <img src="{{ url_for('routes.photo_src', filename=p.thumb) }}" alt="{{ p.description }}" loading="lazy">
        </a>
      </li>
      {% endfor %}
      <li></li>
    </ul>

    {% if page_previous or page_next %}
      <div class="btn-group" role="group">
        {% if page_previous %}
        <a href="{{ page_previous }}">
          <button type="button" class="btn btn-lg btn-primary">Previous page</button>
        </a>
        {% endif %}

        {% if page_next %}
        <a href="{{ page_next }}" style="padding-left:20px;">
          <button type="button" class="btn btn-lg btn-primary">Next page</button>
        </a>
        {% endif %}
      </div>
    {% endif %}
  </div>
{% endblock %}

photo_site/templates/index_album.html
{% extends "base.html" %}
{% block content %}
  {% block title %}{{ album.name }}{% endblock %}
  {% include "flash.html" %}
  <div class="container-fluid navtop">
    <h4 style="margin-left:4px;">Album: {{ album.name }}</h4>

    {% if album.description and photos %}
      <col-md-6>
      <p style="margin-left:4px;">{{ album.description }}</p>
      </col-md-6>
    {% endif %}
    {% if not photos %}
      Out of photos (ノಠ益ಠ)ノ彡┻━┻
    {% endif %}
    <ul class="stream" style="margin-top:38px;">
      {% for p in photos %}
      <li>
        <a href="{{ url_for('routes.album_photo_view', album_id=album.id, photo_id=p.id) }}">
          <img src="{{ url_for('routes.photo_src', filename=p.thumb) }}" alt="{{ p.description }}" loading="lazy">
        </a>
      </li>
      {% endfor %}
      <li></li>
    </ul>

    <div class="btn-group" role="group">
      <a href="{{ page_previous }}">
        <button type="button" class="btn btn-secondary">Previous page</button>
      </a>

      <a href="{{ page_next }}" style="padding-left:20px;">
        <button type="button" class="btn btn-secondary">Next page</button>
      </a>
    </div>

  </div>
{% endblock %}

photo_site/templates/login.html
{% extends "base.html" %}
{% block content %}


<div class="container navtop">
  {% include "flash.html" %}

  <div class="row">
    <div class="col-md-3">
      <form action="{{ url_for('routes_admin.login') }}" method="POST">
        <div class="mb-3">
          <label for="pwd">Password:</label>
          <input type="text" name="pwd" class="form-control" id="pwd">
        </div>

        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>

</div>

{% endblock %}

photo_site/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/" style="margin-left:18px;">
      <img src="/static/logo.png" alt="" width="52" height="28" class="d-inline-block align-text-top">
    </a>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
      {% if '/a/' in request.path %}
        <a class="nav-link" aria-current="page" href="{{ url_for('routes.index') }}">Photos</a>
        <a class="nav-link active" href="{{ url_for('routes.albums_view') }}">Albums</a>
        <a class="nav-link" href="{{ url_for('routes.about') }}">About</a>
      {% elif 'about' in request.path %}
        <a class="nav-link" aria-current="page" href="{{ url_for('routes.index') }}">Photos</a>
        <a class="nav-link" href="{{ url_for('routes.albums_view') }}">Albums</a>
        <a class="nav-link active" href="{{ url_for('routes.about') }}">About</a>
      {% else %}
        <a class="nav-link active" aria-current="page" href="{{ url_for('routes.index') }}">Photos</a>
        <a class="nav-link" href="{{ url_for('routes.albums_view') }}">Albums</a>
        <a class="nav-link" href="{{ url_for('routes.about') }}">About</a>
      {% endif %}
      </div>
      <div class="navbar-nav" style="float: right">
        {% if current_user.is_authenticated %}
          <a class="nav-link" href="/admin/">Admin</a>
        {% endif %}
        <!-- <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
      </div>
    </div>
  </div>
</nav>

photo_site/templates/photo_view.html
{% extends "base.html" %}
{% block content %}

    {% block title %}
      {% if photo.title %}
        {{ photo.title }}
      {% else %}
        Photo
      {% endif %}
    {% endblock %}

  {% set url = url_for('routes.photo_src', filename=photo.filename) %}
  {% set is_auth = current_user.is_authenticated %}

  {% if photo.landscape %}
    <div class="container-xl navtop">
  {% else %}
    <div class="container-xl container-xl-portrait navtop">
  {% endif %}
    {% include "flash.html" %}
    <div class="row photo-view">

      {% if photo.landscape %}
        <div class="col-md-12 ">
      {% else %}
        <div class="col-md-6">
      {% endif %}

      {% if previous_photo %}
      <a href="{{ previous_photo }}" class="pagination" style="left:0">
        <div><i class="fa left fa-arrow-left" style="padding-left: 20px;"></i></div>
      </a>
      {% endif %}

      {% if next_photo %}
      <a href="{{ next_photo }}" class="pagination" style="right:0">
        <div><i class="fa right fa-arrow-right" style="padding-right: 20px;"></i></div>
      </a>
      {% endif %}

      <img class="{% if photo.landscape %}landscape{% else %}portrait{% endif %}" src="{{ url }}" alt="" class="img-fluid w-100" />
      </div>

      {% if photo.landscape %}
      <div class="col-md-6" style="margin-top:20px;">
      {% else %}
      <div class="col-md-6" style="padding-left: 20px;">
      {% endif %}
        <form action="{{ url_for('routes_admin.photos_edit', p_ids=photo.id) }}" method="POST">
          {% if is_auth %}
            <div class="mb-3">
              <label for="title">Title</label>
              <input id="title" name="title" placeholder="..." type="text" value="{{ photo.title }}" class="form-control">
            </div>
          {% elif photo.title %}
            <h2>{{ photo.title }}</h2>
          {% endif %}

          {% if is_auth %}
          <div class="mb-3">
            <label for="description">Description</label>
            <textarea id="description" placeholder="..." name="description" cols="40" rows="5" style="resize: none;" class="form-control">{{ photo.description }}</textarea>
          </div>
          {% elif photo.description %}
            <p>{{ photo.description }}</p>
          {% endif %}

          {% if not is_auth %}
          <ul>
            <li>
              <i class="fa fa-eye"></i> {{ photo.views }}
            </li>

            {% if photo.date_taken %}
            <li>
              <i class="fa fa-clock"></i> {{ photo.date_taken.strftime('%Y-%m-%d') }}
            </li>
            {% endif %}

            <li>
              <i class="fa fa-ruler-combined"></i> {{ photo.width }} x {{ photo.height }}
            </li>

            {% if photo.camera %}
            <li>
              <i class="fa fa-camera"></i> Canon A-1
            </li>
            {% endif %}

            {% if photo.optics %}
            <li>
              <i class="fa fa-glasses"></i> {{ photo.optics }}
            </li>
            {% endif %}

            {% if photo.location %}
            <li>
              <i class="fa fa-location-arrow"></i> {{ photo.location }}
            </li>
            {% endif %}
          </ul>
          {% endif %}

          {% if photo.album_ids and not is_auth %}
            {% if photo.album_ids | length == 1 %}
              <h4>Album</h4>
            {% else %}
              <h4>Albums</h4>
            {% endif %}
            <ul>
            {% for a in albums %}
              {% if a.id in photo.album_ids %}
                <li>
                  <a href="{{ url_for('routes.album_view', album_id=a.id) }}"><i class="fa fa-images"></i> {{ a.name }}</a>
                </li>
              {% endif %}
            {% endfor %}
            </ul>
          {% endif %}

          {% if is_auth %}
          <div class="mb-3">
            <label for="location">Location</label>
            <input id="location" name="location" value="{{ photo.location }}" placeholder="" type="text" class="form-control">
          </div>

          <div class="mb-3">
            <label for="camera_model">Camera model</label>
            <input id="camera_model" name="camera_model" value="{{ photo.camera }}" placeholder="" type="text" class="form-control">
          </div>

          <div class="mb-3">
            <label for="optics">Optics</label>
            <input id="optics" name="optics" value="{{ photo.optics }}" placeholder="" type="text" class="form-control">
          </div>

          <div class="mb-3">
            <label for="date_taken">Date taken</label>
            <input id="date_taken" name="date_taken" value="{{ photo.date_taken }}" placeholder="" type="text" class="form-control">
          </div>

          {% if albums %}
            <br>
            <div class="mb-3">
              <h4>Albums</h4>
              <div>
                {% for a in albums %}
                <div class="custom-controls-stacked">
                  <div class="custom-control custom-checkbox">
                    <input name="albums" id="checkbox_{{ loop.index }}" type="checkbox" {% if a.id in photo.album_ids %}checked="checked"{% endif %} class="custom-control-input" value="{{ a.id }}">
                    <label for="checkbox_{{ loop.index }}" class="custom-control-label">{{ a.name }}</label>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          {% endif %}

          <br>

          <div class="btn-group" role="group">
            <a href="{{ url_for('routes_admin.photo_delete', photo_id=photo.id) }}">
              <button type="button" class="btn btn-danger">Delete</button>
            </a>
            <button type="button" class="btn btn-secondary"></button>
            <button name="submit" type="submit" class="btn btn-primary">Update</button>
          </div>

          {% endif %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

photo_site/templates/photos_edit.html
<!-- batch editing multiple photos at once -->

{% extends "base.html" %}
{% block content %}
  {% include "flash.html" %}
  <div class="container-fluid navtop">
    <ul class="stream">
      {% for p in photos %}
      <li class="small">
        <a href="{{ url_for('routes.photo_view', photo_id=p.id) }}">
          <img src="{{ url_for('routes.photo_src', filename=p.thumb) }}" alt="{{ p.description }}" loading="lazy">
        </a>
      </li>
      {% endfor %}
      <li class="small"></li>
    </ul>
  </div>

  <hr>

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h4>Batch edit photos</h4>
        <form action="{{ url_for('routes_admin.photos_edit', p_ids=p_ids) }}" method="POST">
          <div class="mb-3">
            <label for="camera_model">Camera model</label>
            <input id="camera_model" name="camera_model" placeholder="Canon A-1..." type="text" class="form-control">
          </div>

          <div class="mb-3">
            <label for="optics">Optics</label>
            <input id="optics" name="optics" placeholder="FD 50mm T1.8..." type="text" class="form-control">
          </div>

          <div class="mb-3">
            <label for="date_taken">Date taken</label>
            <input id="date_taken" name="date_taken" placeholder="2011-12-24" type="text" class="form-control">
          </div>

          <div class="mb-3">
            <label for="location">Location</label>
            <input id="location" name="location" placeholder="Amsterdam..." type="text" class="form-control">
          </div>

          {% if albums %}
            <div class="mb-3">
              <h4>Albums</h4>
              <div>
                {% for a in albums %}
                <div class="custom-controls-stacked">
                  <div class="custom-control custom-checkbox">
                    <input name="albums" id="checkbox_{{ loop.index }}" type="checkbox" class="custom-control-input" value="{{ a.id }}">
                    <label for="checkbox_{{ loop.index }}" class="custom-control-label">{{ a.name }}</label>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          {% endif %}

          <br>
          <div class="mb-3">
            <button name="submit" type="submit" class="btn btn-primary">edit album</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}